### ISSUE TITLE
Compiler errors -- Visual Studio 2015

### ISSUE THREAD

**Issue by Cybernide** [SteerSuite/Release#4]
Getting C3848 errors in Visual Studio 2015. Lines 2022, 2027, 2037 in xtree file of steerlib. 

The descriptions are all roughly like this:
"expression having type 'const SteerLib::CompareCosts<PlanningState,PlanningAction>' would lose some const-volatile qualifiers in order to call 'bool SteerLib::CompareCosts<PlanningState,PlanningAction>::operator ()(const SteerLib::BestFirstSearchNode<PlanningState,PlanningAction> &,const SteerLib::BestFirstSearchNode<PlanningState,PlanningAction> &)'"

Any ideas?

**Comment by Neo-X** [comment]
Hello,

I just download and compiled the master branch without that issue. Can you give me some more info about where in the code this error is occurring? You say Lines 2022, 2027, 2037 in xtree file of steerlib. I don't think there is a xtree file in steerlib. Maybe you could attach the link to the code from the github repo?

**Comment by Cybernide** [comment]
Sorry, I was mistaken about the location. The xtree file is in the "Microsoft Visual studio 14.0/include/VC" folder and this happens when I try to build steerlib.

Let me try out your solution and I'll get back to you. Thanks!

**Comment by Cybernide** [comment]
Hi. It builds now. New problems, but I'll open up separate issues for them. Thank you.
